### ISSUE TITLE
Bower Installer and Paths

### ISSUE THREAD

**Issue by toddmbloom** [rquadling/bower-installer#110]
Hello!

I see in the documentation that you can use {name} in your path declarations to separate your files into project paths but for some reason whenever I run bower-installer without using that in my bower.json, it still separates each file into project_name/\* instead of putting it in the root of whatever source is being imported.

Here is my bower.json:

```
  "install": {
    "path": {
      "css": "stylesheets",
      "js": "javascripts",
      "eot": "fonts/",
      "svg": "fonts/",
      "ttf": "fonts/",
      "woff": "fonts/"
    },
    "sources": {
      "material-ui-sass": [
        "bower_components/material-ui-sass/material-design-fonticons/fonts/mdfonticon.*",
        "bower_components/material-ui-sass/material-ui-icons/fonts/material-ui-icons.*"
      ],
      "materialize": [
        "bower_components/materialize/font/roboto/Roboto-*.ttf",
        "bower_components/materialize/font/material-design-icons/Material-Design-Icons.*",
        "bower_components/materialize/js/*.js"
      ]
    },
    "ignore": ["jquery"]
  }
```

Which results in:

```
fonts\material-ui-sass\....
fonts\materialize\...
```

How can I tell it to not use prefixes when importing? 

Thanks!

**Comment by quoideneuf** [comment]
+1

**Comment by quoideneuf** [comment]
I was able to work around this like this:

```javascript
  "install": {
    "path": {
      "js": "vendor/assets/javascripts"
    },
    "sources": {
      "jquery.hotkeys": {
        "mapping": [
          {"bower_components/jquery.hotkeys/jquery.hotkeys.js": "../jquery.hotkeys.js"}
          ]
      }
    }
}
```
But it still created the subdirectories...

**Comment by zkimyes** [comment]
seems i have the same problem

**Comment by startupthekid** [comment]
I'm having the same problem too, my solution was to do exactly the same thing, prefix the file name with `../` like so:
```
{
    "name": "MEAN-seed",
    "version": "1.0.0",
    "dependencies": {
        "angular-bootstrap": "latest",
        "font-awesome": "latest",
        "animate.css": "latest",
        "angular": "latest",
        "angular-route": "latest",
        "jquery": "latest"
    },
    "install": {
    	"path": "js/lib/",
    	"sources": {
    		"angular-bootstrap" : "bower_components/angular-bootstrap/angular-bootstrap.min.js",
    		"angular" : {
    			"mapping": [
    				{"bower_components/angular/angular.min.js": "../angular.min.js"}
    			]
    		},
    		"jquery" : {
		        "mapping": [
		          {"bower_components/jquery/dist/jquery.min.js": "../jquery.min.js"}
		        ]
		      }
    	}
    }
}
```

Unfortunately even though the files are all getting created in my `/js/lib` directory, the folders are too, with nothing in them. Not a major issue, more of an annoyance than anything else.

**Comment by rquadling** [comment]
Happy to fix if anyone here can help out.

I'm new to JS packages like this, but willing to learn. What options exist for realtime debugging/stepwise execution?

**Comment by sbibauw** [comment]
@rquadling It seems there was a fix on [#128](https://github.com/rquadling/bower-installer/pull/128), but not released to `npm`?

**Comment by rquadling** [comment]
I took over the project on 2016/1205 and did an initial release of https://github.com/rquadling/bower-installer/releases/tag/v1.3.0.

That release includes the merge of that PR 339bbceed58b03d66cf099a7d4ab9e839a23987c

**Comment by sbibauw** [comment]
@rquadling Great! So that means the fix is already there. It is just not documented yet, and I must say I am not sure I get how to change this `options.includePackageNameInInstallPath` setting. I suppose there should be some optional CLI argument (something like `bower-installer --nopackagename`)?

**Comment by rquadling** [comment]
Please see the v1.3.6 https://github.com/rquadling/bower-installer#excluding-package-name-from-destination-folder
