### ISSUE TITLE
How do I automate bower-installer after a bower install

### ISSUE THREAD

**Issue by MMrR0b0TT** [rquadling/bower-installer#133]
Hi guys,

I'd like to know how to automate the bower-installer after each "bower install" using Visual Studio 2015. 

Has someone any suggestion?

**Comment by lidia-freitas** [comment]
:+1:

**Comment by rquadling** [comment]
Why not just run `bower-installer -pr` rather than `bower install` ?

**Comment by rquadling** [comment]
But you could create a `.bowerrc` with content along these lines ...

```
{
  "scripts": {
    "postinstall": "bower-installer"
  }
}
```

maybe.

**Comment by namtab00** [comment]
if you're using gulp, install gulp-shell

then in gulpfile.js

    var shell = require('gulp-shell');
    gulp.task('bower-installer', shell.task([
	'bower-installer'
    ]))

**Comment by rquadling** [comment]
Closing as several solutions provided.
