### ISSUE TITLE
Proposal to allow copying source folders to a subfolder in target

### ISSUE THREAD

**Issue by mathieuvanloon** [rquadling/bower-installer#142]
Hi,

I'd like to copy several themes from jquery-ui to the target folder, preserving their name and structure. This doesn't seem to be possible. You can glob: 

```
  "jquery-ui": {
    "mapping": [
      { "bower_components/jquery-ui/jquery-ui.min.js": "jquery-ui.min.js" },
      "bower_components/jquery-ui/themes/smoothness/**"
    ]
  },
```

but then the contents of smoothness will be transferred to the jquery-ui/ folder in target. Instead I would like to see them transferred to jquery-ui/smoothness/. What about the following solution:

```
  "jquery-ui": {
    "mapping": [
      { "bower_components/jquery-ui/jquery-ui.min.js": "jquery-ui.min.js" },
      { "bower_components/jquery-ui/themes/smoothness/**": "smooty" },
      { "bower_components/jquery-ui/themes/base/**": "base" }
    ]
  },
```

Note the two mappings for smoothness and base. Both keys end in /**, indicating the request to copy the whole subfolder from source. both are mapped to an output folder. In this case, the contents of the smoothness theme will be copied to the subfolder jquery-ui/smooty/ in the target, preserving the original structure.

If there is any interest I'll gladly prepare a patch for inclusion as we have the code running already locally.

**Comment by tip2tail** [comment]
+1 for this

**Comment by rquadling** [comment]
https://github.com/rquadling/bower-installer/pull/143
