### ISSUE TITLE
bower-installer: command not found

### ISSUE THREAD

**Issue by roseanngabon** [rquadling/bower-installer#145]
I followed installation instruction below but I still won't be able to use the bower installer.

> Install bower-installer by executing
> <code>npm install -g bower-installer</code>
> From the terminal in the same directory as your bower.json file, enter:
> <code>bower-installer</code>

 I'm using bower version 1.7.1 in Windows 8.1 with GitBash(no Mintty). Please help. Thank you

**Comment by Crunkelton** [comment]
I am having the same problem on windows 7

bower version 1.7.7

**Comment by rquadling** [comment]
Are you still having a problem running bower-installer?

**Comment by matt-liu** [comment]
I am also having this issue with Git Bash on Windows 7 SP1

**Comment by rquadling** [comment]
If you install bower-installer locally, you have to access it via the local node binaries path.
For me, this is ./node_modules/.bin (I'm on OSX). For Windows try .\node_modules\.bin.

This is where all your local installed binaries are held. Nothing special about bower-installer.

**Comment by rquadling** [comment]
The node package manager (npm) manages where it installs binaries, both globally and locally.

To find where your node installation is placing the binaries, you have 2 commands you can run.

`npm bin -g` and `npm bin`

If you have these locations in your path, then bower-installer will operate without needing the path.
