### ISSUE TITLE
Can you save all Bower Components to Root vs. Root + Component's Folder Name?

### ISSUE THREAD

**Issue by rooksstrife** [rquadling/bower-installer#146]
I am trying to save all my bower components to src/css and src/js.  I do not want src/css/animate/animate.css etc... and src/js/angular/angular.js etc...  I want all css and js flat.  Is this possible?

**Comment by machinavn** [comment]
Same problem. Because it's too annoying and some files like bootstrap.css reference to other files like ../fonts/....ttf like that, But when I copy fonts folder it become bootstrap/fonts/.ttf so the bootstrap.css can't reference.

**Comment by machinavn** [comment]
see https://github.com/blittle/bower-installer/pull/127

**Comment by mstoltenburg** [comment]
I'm looking for this too

**Comment by mstoltenburg** [comment]
This is configurable - it's just not documented anywhere. Just add `options` to your bower.json.
```json
  "install": {
    "options": {
      "includePackageNameInInstallPath": false
    },
    "path": "foo"
  }
```

**Comment by rquadling** [comment]
I'm just adding some tests and documentation for this issue. Should be done within the next couple of hours.
