### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by blittle** [rquadling/bower-installer#149]
I am no longer able or interested in maintaining this project. Is anyone in the community interested in doing so?

**Comment by rquadling** [comment]
As you had no replies, I've cross posted to the bower issues page. Hopefully someone with more JS skills than me will step in.

**Comment by rquadling** [comment]
Well, I have to say that the responses haven't been great!

I'm a user of bower-installer, but my JS skills aren't great.

I'm happy to take over the repo for maintenance/patching, but probably not future development.

That may be enough for a lot of users.

If that is enough, then go for it.

**Comment by blittle** [comment]
@rquadling it is a great opportunity for you to learn and get involved, I might occasionally be able to give you some feedback if you'd like.

**Comment by rquadling** [comment]
Well, got for it.

I can see Travis-CI can run JS tests. Hopefully there is some code coverage analysis capability. That way I can at least see what is broken or untested.

**Comment by rquadling** [comment]
At least until someone else volunteers.

**Comment by blittle** [comment]
Granted collaborator access. FYI, @g105b also started helping out a while back. Not sure if he has any interest anymore.

**Comment by g105b** [comment]
bower-installer was the answer to many bower issues, and I contributed the part that was missing for me, however I have moved on from using bower in projects all together so no longer have this project on my radar.

I'll happily guide/mentor anyone in making their contributions to the project, but I won't be contributing myself anytime soon.

**Comment by blittle** [comment]
@g105b That has really been my dilemma as well. I have totally moved all of my work to either webpack or JSPM. I have no use anymore for for bower :( I'd be willing to help out with guidance, but I don't think I'm the best one to lead the project given I lack a vested interest. If anyone really wants to take charge of the project, I am more than willing to transfer ownership, but I'd prefer to wait to see if anyone steps up to the plate.

**Comment by g105b** [comment]
Agreed. This kind of project survives on passion. Do you think a message in the readme advertising a new project owner would be a good idea?

**Comment by blittle** [comment]
@g105b added :)

**Comment by thinkxl** [comment]
I may be able to help, I have used bower-installer on some projects and it helped me a lot. Let me know if there is an active plan or actions that need to be done.

**Comment by blittle** [comment]
@thinkxl I think generally the project needs the issue list cleaned up as well as it needs to be upgraded to the latest version of bower. Beyond that, it would probably be best for someone to step in and take charge of bower-installer's future direction.

**Comment by thinkxl** [comment]
@blittle It sounds fun, I will dig into the issues and see what needs to be done to sync it with current Bower version

**Comment by dezkareid** [comment]
@blittle I make a fork of the project and I include a little method to add the minified files, later I will make a pull request, I wanna be a maintainer to contribute to the open-source :)

**Comment by mautematico** [comment]
This is my first day with bower-installer, since mozilla/localforage can't be imported es6-way.
I hope you guys find an amazing path for this great tool. My skills are probably not yet ready to maintain this project, buy I'll put this on my radar. :)

**Comment by eman1986** [comment]
I'd love to take part in this, but I'm not a nodeJs developer.

I really love bower-installer

**Comment by machinavn** [comment]
I love bower-installer but when I run bower-installer, it's auto find files's path to grab, and sometimes It doesn't grab files I want like Bootstrap. ( I need bootstrap.css not .less) . Want to grab right files need configuration which is pain in the ass. And I think when it grab jquery.js it should be place to `src/vendor/jquery.js` so I can maintain source files, not `src/vendor/jquery/jquery.js`. I prefer do copy those files on my own.

**Comment by kimus** [comment]
@blittle Is there a new owner for this project? @dezkareid are you the new owner? If so this issues should be closed.

I contributed to this project in the past ('Configurable paths') and I think there's a need to address some of the issues that are reported. Like supporting mapping with glob, this issues already have pull request (see #143) and no action was made. I will be glad to help on this again.

**Comment by nickion** [comment]
Would be good to see this project alive again at least to accept pull requests. I've forked and added a quick fix for directory copying that we needed, so you can write something such as:

```
 "jquery-ui" : [
   "bower_components/jquery-ui/jquery-ui.min.js",
   "bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css",
   { "bower_components/jquery-ui/themes/smoothness/images/" : "images/" }
],
```

which may also be similar to #143. Is there any consensus on 1 or 2 "must have" changes?

**Comment by jesseyuen** [comment]
@nickion ^ Thats definitely number one for me :)

**Comment by blittle** [comment]
Who would be willing to take ownership? Like I stated above, I don't have the time nor interest to continue supporting bower-installer.

**Comment by rquadling** [comment]
I'll take it. I am collaborator already and actively work on various PHP based projects. This would be my first JS based one.

**Comment by rquadling** [comment]
Hi.

I have received ownership of this project.

I'd like to thank Bret for the time and energy he put into this project and I promise to look after it!

I'm going to close this issue now.

If anyone has any outstanding points, please open a new issue, referring to this one if necessary.

Thanks,

Richard.
