### ISSUE TITLE
npm install -g bower-installer taking long and not working at all.

### ISSUE THREAD

**Issue by pratik916** [rquadling/bower-installer#151]
This is the terminal response.

sudo npm install -g bower-installer
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
fetchMetadata -> network  \ |###########--------------------------------------|

And it stops from here.

npm version => 3.8.5

Alredy done:
Checked internet connection.
Cleared npm cache.

**Comment by mautematico** [comment]
I just installed bower-installed with npm 3.8.6.
Are you able to update npm to 3.8.6+ and report back if it solves the issue, please?

**Comment by rquadling** [comment]
Closed - no feedback
