### ISSUE TITLE
npm access

### ISSUE THREAD

**Issue by blittle** [rquadling/bower-installer#159]
@rquadling what is your npm user name? I'll give you access to the npm package.

**Comment by rquadling** [comment]
Just created one ... ~rquadling

**Comment by blittle** [comment]
I just added you!

**Comment by blittle** [comment]
@rquadling please let me know if you have questions about working with npm.

**Comment by rquadling** [comment]
Will do! Thank you.

**Comment by rquadling** [comment]
Just published v1.3.2!

I suppose it should be possible to auto publish from github, similar to PHP+Packagist?

**Comment by blittle** [comment]
@rquadling not that I know of

**Comment by rquadling** [comment]
Will have to remember to run the patch and publish mechanisms when I need to.
