### ISSUE TITLE
Using `path` to install files to multiple locations by file type behaves differently than using a single global `path` for all files.

### ISSUE THREAD

**Issue by ctumolosus** [rquadling/bower-installer#36]
Using the following configuration:

```
"dependencies": {
    "requirejs": "~2.1.8",
    "requirejs-text": "~2.0.10"
},
"install": {
  "path": "public/js/lib",
  "sources": {
    "requirejs-text": "bower_components/requirejs-text/text.js" 
  }
}
```

Yields the following file structure:

```
/public/js/lib/requirejs/require.js
/public/js/lib/requirejs-text/text.js
```

While using this configuration:

```
"dependencies": {
    "requirejs": "~2.1.8",
    "requirejs-text": "~2.0.10"
},
"install": {
  "path": {
    "js": "public/js/lib",
    "css": "public/css/lib"
  },
  "sources": {
    "requirejs-text": "bower_components/requirejs-text/text.js" 
  }
}
```

Yields the following file structure:

```
/public/js/lib/require.js
/public/js/lib/text.js
```

Notice how the main files became children of the `public/js/lib` directory, rather than being enclosed within a sub-directory with the library name.

Is there anyway to get the latter to look like the former? 

Also, is there anyway to tell the script to place `text.js` within `public/js/lib/requirejs/`?

**Comment by ctumolosus** [comment]
I'm closing to clean up my backlog of issues.

**Comment by rquadling** [comment]
I thought this was fixed?

Using: https://github.com/rquadling/bower-installer/blob/master/test/multiPathWithoutPackageName/bower.json and the test to prove it:
https://github.com/rquadling/bower-installer/blob/master/bower-installer.spec.js#L448, no package names in path when using multiple paths defined by extension.

Whilst the tests haven't been released, https://github.com/rquadling/bower-installer/compare/v1.3.6...master shows no diff other than tests between master and the v1.3.6 release.

If you are experiencing anything different, please let me know and I will attempt to fix.

I only took over the project a short while ago.
