### ISSUE TITLE
custom install path - with version

### ISSUE THREAD

**Issue by atian25** [rquadling/bower-installer#87]
```
  components
    - bootstrap
      - 2.0.0
      - 2.0.1
    - angular
      - 1.2.0
      - 1.3.0rc1
```

**Comment by youys** [comment]
bower.json of bootstrap has no "version" key, in .bower.json  has.

**Comment by g105b** [comment]
while we're at it let's add the maintainer's name in the directory structure

```
components
    - twitter
        - bootstrap
          - 2.0.0
          - 2.0.1
    - angular
        - angular.js
          - 1.2.0
          - 1.3.0rc1
```

This is actually exactly how the [Component package manager](https://github.com/componentjs/component) works.
